{% set python_min = "3.11" %}
{% set name = "nomad-camels-driver-PID" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name.replace('-', '_').lower() }}/{{ name.replace('-', '_').lower() }}-{{ version }}.tar.gz
  sha256: b912cbb28cb315b19bc9d4b3576e9b17fded7f5d6d1f8b7a32623118e882d1da

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - nomad-camels >=1.8.3
    - python >={{ python_min }}
    - simple-pid

test:
  imports:
    - nomad_camels_driver_PID
  commands:
    # - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/FAU-LAP/CAMELS_drivers
  summary: This package provides everything to run a PID Controller with.
  license: LGPL-2.1-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
